# Site settings
title: The 9 Minute Snooze
email: aaron+blog@9minutesnooze.com
#description: > # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.9minutesnooze.com" # the base hostname & protocol for your site
twitter_username: aaronbbrown777
github_username:  9minutesnooze

# Build settings
markdown: kramdown

highlighter: pygments
layout: default
comments: true
